# 1. 首页顶部全屏大图（可以换成你喜欢的二次元插画或壁纸外链）
index_img: /img/rei.png

# 2. 网页全局背景底图（透过半透明卡片看到的底层壁纸）
background: /img/ss.jpg

# 3. 首页大图正中央的打字机动效（截图中的名言台词效果）
subtitle:
  enable: true
  loop: true          # 是否循环打字
  source: false       # 设为 false 使用自定义文本
  sub:
    - "宅文化的阅读、研究、与批评"
    - "表象、媒介、身体..."
    - "动画、漫画、游戏..."

# 4. 右侧作者名片栏
avatar:
  img: /img/avatar.png # 头像链接
  effect: true        # 鼠标悬停头像旋转特效


# 5. 顶部导航菜单
menu:
  首页: / || fas fa-home

  研究||fas fa-search:
     研究总览: /research/ || fas fa-compass
     宅文化批评: /research/otaku/ || fas fa-book-open
     动画研究: /research/anime/ || fas fa-film
     漫画研究: /research/manga/ || fas fa-images
     游戏研究: /research/game/ || fas fa-gamepad
     研究方法: /research/methods/ || fas fa-flask

  资料库||fas fa-database:
    资料总览: /library/ || fas fa-compass
    书籍: /books/ || fas fa-book
    论文: /papers/ || fas fa-file-alt
    人物: /people/ || fas fa-user
    理论词典: /theory/ || fas fa-list

  大学院考学||fas fa-graduation-cap:
    入门: /graduate/ || fas fa-compass
    院校数据库: /graduate/schools/ || fas fa-university
    教授数据库: /graduate/professors/ || fas fa-user
    研究计划书: /graduate/research-plan/ || fas fa-edit
    过去问: /graduate/past-exams/ || fas fa-question-circle
    出愿: /graduate/application/ || fas fa-paper-plane
    面试: /graduate/interview/ || fas fa-comments

  咨询服务: /consulting/ || fas fa-comments
  关于本站: /about/ || fas fa-info-circle
  # 侧边栏
aside:
  enable: true
  position: right

  card_author:
    enable: true
    description: "QQ群1090084816二次元吹水杂谈考学什么都行，欢迎来玩～"
    button:
      enable: true
      icon: fas fa-circle-info
      text: 关注我
      link: /about/

  card_announcement:
    enable: true
    content: "整理一些宅文化批评相关的阅读、研究资料，以及日本表象文化大学院的考学信息。站长仍在努力中～"
